repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]
